### ISSUE TITLE
Back to back Bazel commands fail with strange error

### ISSUE THREAD

**Issue by mattmoor** [google/subpar#29]
You can see this in my [initial](https://travis-ci.org/google/containerregistry/builds/221943085) attempt at a `.travis.yml` for `google/containerregistry`:

```
ERROR: /home/travis/build/google/containerregistry/BUILD.bazel:28:1: Building par file //:puller.par failed: Process exited with status 1 [sandboxed].
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/__main__.py", line 28, in <module>
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/cli.py", line 114, in main
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/python_archive.py", line 113, in create
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/python_archive.py", line 250, in write_zip_data
  File "bazel-out/host/bin/external/subpar/compiler/compiler.par/subpar/compiler/stored_resource.py", line 51, in store
  File "/usr/lib/python2.7/zipfile.py", line 1118, in write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: 'bazel-bin/puller.runfiles/__init__.py'
Use --strategy=PythonCompile=standalone to disable sandboxing for the failing actions.
```

**Comment by mattmoor** [comment]
@damienmg FYI

**Comment by duggelz** [comment]
I suspect my Bazel rule is not properly setting up the dependencies on the runfiles (which have kind of a weird place in Bazel's dependency resolution system).

**Comment by jmillikin-stripe** [comment]
I think this is a bug in `containerregistry/BUILD.bzl`. It contains this target:

```
py_library(
   name = "containerregistry",
   srcs = glob(["**/*.py"]),
   deps = [ ... ]   
)
```

If you have such a glob in the top-level `BUILD`, it will pick up files from the `bazel-*` convenience symlinks.

**Comment by mattmoor** [comment]
Good spot, thanks.
