### ISSUE TITLE
compiler can't find python binary

### ISSUE THREAD

**Issue by benley** [google/subpar#35]
On some systems I see errors like the following:

```
benley@alnitak:~/pm/pi-k8s$ bazel build  @subpar//compiler:compiler.par --verbose_failures --strategy=PythonCompile=standalone                               
INFO: Found 1 target...           
ERROR: /home/benley/.cache/bazel/_bazel_benley/9e259f4d6c3d097d1daa32f0372be769/external/subpar/compiler/BUILD:40:1: Building par file @subpar//compiler:compiler.par failed: compiler failed: error executing command                                                                
  (cd /home/benley/.cache/bazel/_bazel_benley/9e259f4d6c3d097d1daa32f0372be769/execroot/pi-k8s && \                                        
  exec env - \                    
  bazel-out/host/bin/external/subpar/compiler/compiler --manifest_file bazel-out/local-fastbuild/bin/external/subpar/compiler/compiler.par_SOURCES --outputpar bazel-out/local-fastbuild/bin/external/subpar/compiler/compiler.par --stub_file bazel-out/local-fastbuild/bin/external/subpar/compiler/compiler external/subpar/compiler/compiler.py): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.                    
Traceback (most recent call last):
  File "bazel-out/host/bin/external/subpar/compiler/compiler", line 168, in <module>                                                       
    Main()                        
  File "bazel-out/host/bin/external/subpar/compiler/compiler", line 148, in Main                                                           
    raise AssertionError('Could not find python binary: ' + PYTHON_BINARY)                                                                 
AssertionError: Could not find python binary: python                 
Target @subpar//compiler:compiler.par failed to build                
INFO: Elapsed time: 0.103s, Critical Path: 0.03s
```

On others it works.

The difference appears to be in the behaviour of `env -` across linux distributions.  On Ubuntu and Debian, the resulting "empty" environment still has $PATH set to a default value:

```
benley@aram:~$ env - bash -c set
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="3" [2]="30" [3]="1" [4]="release" [5]="i586-pc-linux-gnu")
BASH_VERSION='4.3.30(1)-release'
DIRSTACK=()
EUID=1009
GROUPS=()
HOSTNAME=aram
HOSTTYPE=i586
IFS=$' \t\n'
MACHTYPE=i586-pc-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
PPID=6844
PS4='+ '
PWD=/home/benley
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
TERM=dumb
UID=1009
_=bash
```
(same output on ubuntu 16.04)

On at least one other distro (NixOS linux), there seems to be no such default PATH:

```
benley@alnitak:~$ env - bash -c set
BASH=/run/current-system/sw/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="4" [2]="12" [3]="1" [4]="release" [5]="x86_64-unknown-linux-gnu")
BASH_VERSION='4.4.12(1)-release'
DIRSTACK=()
EUID=1000
GROUPS=()
HOSTNAME=alnitak
HOSTTYPE=x86_64
IFS=$' \t\n'
MACHTYPE=x86_64-unknown-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/no-such-path
PPID=3931
PS4='+ '
PWD=/home/benley/pm/pi-k8s
SHELL=/run/current-system/sw/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
TERM=dumb
UID=1000
_=bash
```

It's not entirely clear to me why PATH gets set like that, but it certainly breaks the compiler's build.

**Comment by benley** [comment]
A bit more digging:

Debian and Ubuntu and various other distros have a default value for PATH **hardcoded into bash** and/or libc.  Not all distributions do that.  Subpar's build is assuming that Python will be found in the PATH that is hardcoded into the shell, which isn't a great assumption.

**Comment by duggelz** [comment]
This error is actually coming from Bazel, not Subpar.  I see a number of other issues filed for Bazel + NixOS so I'm not too surprised.

There relevant code is here: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/stub_template.txt

If NixOS isn't going to set PATH reasonably, or set it differently than other distros, then it might need a completely separate configuration in Bazel (i.e. Linux, Windows, Darwin, Android, ... Nix).

**Comment by benley** [comment]
The thing is, NixOS _does_ set PATH reasonably.  It just doesn't embed its default PATH into /bin/bash like other distros.

**Comment by benley** [comment]
But you are right - this isn't necessarily a subpar bug.
