### ISSUE TITLE
Why does this not work on RHEL 7

### ISSUE THREAD

**Issue by jeb2239** [google/subpar#75]
Just wondering if there is a technical reason for this.

**Comment by duggelz** [comment]
What kind of error message are you getting?  Python 2.6 is a problem, but my Googling says that RHEL 7 ships with Python 2.7.

**Comment by jeb2239** [comment]
some of the tests fail

```
Successfully installed setuptools-0.9.8
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Analysed 62 targets (27 packages loaded).
INFO: Found 32 targets and 30 test targets...
FAIL: //runtime:support_test (see /home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/execroot/subpar/bazel-out/k8-fastbuild/testlogs/runtime/support_test/test.log)
INFO: From Testing //runtime:support_test:
==================== Test output for //runtime:support_test:
....EE
======================================================================
ERROR: test_setup (__main__.SupportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/bazel-sandbox/4866906574489874724/execroot/subpar/bazel-out/k8-fastbuild/bin/runtime/support_test.runfiles/subpar/runtime/support_test.py", line 143, in test_setup
    zip_safe=True)
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/bazel-sandbox/4866906574489874724/execroot/subpar/bazel-out/k8-fastbuild/bin/runtime/support_test.runfiles/subpar/runtime/support.py", line 326, in setup
    _setup_pkg_resources('pkg_resources')
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/bazel-sandbox/4866906574489874724/execroot/subpar/bazel-out/k8-fastbuild/bin/runtime/support_test.runfiles/subpar/runtime/support.py", line 157, in _setup_pkg_resources
    __import__(pkg_resources_name)
  File "/home/vagrant/subpar/.env/lib/python3.6/site-packages/pkg_resources.py", line 1545, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

======================================================================
ERROR: test_setup__extract (__main__.SupportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/bazel-sandbox/4866906574489874724/execroot/subpar/bazel-out/k8-fastbuild/bin/runtime/support_test.runfiles/subpar/runtime/support_test.py", line 168, in test_setup__extract
    success = support.setup(import_roots=['some_root'], zip_safe=False)
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/bazel-sandbox/4866906574489874724/execroot/subpar/bazel-out/k8-fastbuild/bin/runtime/support_test.runfiles/subpar/runtime/support.py", line 326, in setup
    _setup_pkg_resources('pkg_resources')
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/bazel-sandbox/4866906574489874724/execroot/subpar/bazel-out/k8-fastbuild/bin/runtime/support_test.runfiles/subpar/runtime/support.py", line 157, in _setup_pkg_resources
    __import__(pkg_resources_name)
  File "/home/vagrant/subpar/.env/lib/python3.6/site-packages/pkg_resources.py", line 1545, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (errors=2)
================================================================================
ERROR: /home/vagrant/subpar/tests/BUILD:66:1: Building par file //tests:package_f/f.par failed (Exit 1)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bazel-out/host/bin/compiler/compiler.par/__main__.py", line 19, in <module>
  File "bazel-out/host/bin/compiler/compiler.par/subpar/runtime/support.py", line 326, in setup
  File "bazel-out/host/bin/compiler/compiler.par/subpar/runtime/support.py", line 157, in _setup_pkg_resources
  File "/home/vagrant/subpar/.env/lib/python3.6/site-packages/pkg_resources.py", line 1545, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
INFO: Elapsed time: 1.466s, Critical Path: 0.45s
FAILED: Build did NOT complete successfully
//compiler:cli_test                                                   NO STATUS
//compiler:manifest_parser_test                                       NO STATUS
//compiler:python_archive_test                                        NO STATUS
//compiler:stored_resource_test                                       NO STATUS
//tests:basic_nopar_test                                              NO STATUS
//tests:basic_test                                                    NO STATUS
//tests:dir_shadowing_nopar_test                                      NO STATUS
//tests:dir_shadowing_test                                            NO STATUS
//tests:direct_dependency_nopar_test                                  NO STATUS
//tests:direct_dependency_test                                        NO STATUS
//tests:external_workspace_nopar_test                                 NO STATUS
//tests:external_workspace_test                                       NO STATUS
//tests:extract_nopar_test                                            NO STATUS
//tests:extract_test                                                  NO STATUS
//tests:import_root_nopar_test                                        NO STATUS
//tests:import_root_test                                              NO STATUS
//tests:import_roots_nopar_test                                       NO STATUS
//tests:import_roots_test                                             NO STATUS
//tests:indirect_dependency_nopar_test                                NO STATUS
//tests:indirect_dependency_test                                      NO STATUS
//tests:main_boilerplate_nopar_test                                   NO STATUS
//tests:main_boilerplate_test                                         NO STATUS
//tests:pkg_resources_nopar_test                                      NO STATUS
//tests:pkg_resources_test                                            NO STATUS
//tests:shadow_nopar_test                                             NO STATUS
//tests:shadow_test                                                   NO STATUS
//tests:test_compiler_label_wrapper                                   NO STATUS
//tests:version_nopar_test                                            NO STATUS
//runtime:support_test                                                   FAILED in 0.4s
  /home/vagrant/.cache/bazel/_bazel_vagrant/e1bb13c0ba0852c4a2b5e67d0e8cc6ca/execroot/subpar/bazel-out/k8-fastbuild/testlogs/runtime/support_test/test.log

Executed 1 out of 30 tests: 1 fails to build, 1 fails locally and 28 were skipped.
[vagrant@localhost subpar]$ 
```

**Comment by duggelz** [comment]
There is already a CentOS 7 test in the test suite, and a version check in the code, but I guess there is some difference between CentOS 7 and RHEL 7 being exposed here.  It's sort of hard for me to test that environment, unfortunately.

Are you using the `run_tests.sh` script to test?  If so, there should be output lines like `Testing /some/path/python[X.Y]` and `Testing virtualenv tests/requirements-test-[something].txt`.  Can you paste those lines in here?
