### ISSUE TITLE
par file sources have incorrect path when included in workspace

### ISSUE THREAD

**Issue by keith** [google/subpar#89]
With the `par_binary` from [this repo](https://github.com/google/xctestrunner) which is defined as:

```python
package(default_visibility = ["//visibility:public"])

load("@subpar//:subpar.bzl", "par_binary")

py_library(
    name = 'shared',
    srcs = glob(['shared/*.py']),
)

py_library(
    name = 'simulator',
    srcs = glob(['simulator_control/*.py']),
    deps = [
        ':shared',
    ],
)

par_binary(
    name = 'ios_test_runner',
    srcs = glob(
        ['test_runner/*.py'],
        exclude = ['test_runner/TestProject/**']
    ),
    main = 'test_runner/ios_test_runner.py',
    deps = [
        ':shared',
        ':simulator',
    ],
    data = glob(['test_runner/TestProject/**']),
)
```

When building normally in that repo with `bazel build xctestrunner:ios_test_runner.par`, you end up with a valid par file with these SOURCES being used:

```
__main__/xctestrunner/__init__.py 
__main__/xctestrunner/ios_test_runner bazel-out/darwin-fastbuild/bin/xctestrunner/ios_test_runner
__main__/xctestrunner/shared/__init__.py xctestrunner/shared/__init__.py
__main__/xctestrunner/shared/bundle_util.py xctestrunner/shared/bundle_util.py
__main__/xctestrunner/shared/ios_constants.py xctestrunner/shared/ios_constants.py
__main__/xctestrunner/shared/ios_errors.py xctestrunner/shared/ios_errors.py
__main__/xctestrunner/shared/plist_util.py xctestrunner/shared/plist_util.py
__main__/xctestrunner/shared/provisioning_profile.py xctestrunner/shared/provisioning_profile.py
__main__/xctestrunner/shared/xcode_info_util.py xctestrunner/shared/xcode_info_util.py
__main__/xctestrunner/simulator_control/__init__.py xctestrunner/simulator_control/__init__.py
__main__/xctestrunner/simulator_control/simtype_profile.py xctestrunner/simulator_control/simtype_profile.py
__main__/xctestrunner/simulator_control/simulator_util.py xctestrunner/simulator_control/simulator_util.py
__main__/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/project.pbxproj xctestrunner/test_runner/TestProject/TestProject.xcodeproj/project.pbxproj
__main__/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXctest.xcscheme xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXctest.xcscheme
__main__/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXcuitest.xcscheme xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXcuitest.xcscheme
__main__/xctestrunner/test_runner/__init__.py xctestrunner/test_runner/__init__.py
__main__/xctestrunner/test_runner/dummy_project.py xctestrunner/test_runner/dummy_project.py
__main__/xctestrunner/test_runner/ios_test_runner.py xctestrunner/test_runner/ios_test_runner.py
__main__/xctestrunner/test_runner/logic_test_util.py xctestrunner/test_runner/logic_test_util.py
__main__/xctestrunner/test_runner/runner_exit_codes.py xctestrunner/test_runner/runner_exit_codes.py
__main__/xctestrunner/test_runner/test_summaries_util.py xctestrunner/test_runner/test_summaries_util.py
__main__/xctestrunner/test_runner/xcodebuild_test_executor.py xctestrunner/test_runner/xcodebuild_test_executor.py
__main__/xctestrunner/test_runner/xctest_session.py xctestrunner/test_runner/xctest_session.py
__main__/xctestrunner/test_runner/xctestrun.py xctestrunner/test_runner/xctestrun.py
```

When including this repository in your WORKSPACE (instead of using the par files they vendor on GitHub releases) like this:

```python
git_repository(
    name = "subpar",
    remote = "https://github.com/google/subpar",
    tag = "1.3.0",
)

git_repository(
    name = "xctestrunner",
    remote = "https://github.com/google/xctestrunner.git",
    tag = "0.2.5",
)
```

The SOURCES used for building with `bazel build @xctestrunner//xctestrunner:ios_test_runner.par` are:

```
__init__.py 
xctestrunner/__init__.py 
xctestrunner/xctestrunner/__init__.py 
xctestrunner/xctestrunner/ios_test_runner bazel-out/darwin-fastbuild/bin/external/xctestrunner/xctestrunner/ios_test_runner
xctestrunner/xctestrunner/shared/__init__.py external/xctestrunner/xctestrunner/shared/__init__.py
xctestrunner/xctestrunner/shared/bundle_util.py external/xctestrunner/xctestrunner/shared/bundle_util.py
xctestrunner/xctestrunner/shared/ios_constants.py external/xctestrunner/xctestrunner/shared/ios_constants.py
xctestrunner/xctestrunner/shared/ios_errors.py external/xctestrunner/xctestrunner/shared/ios_errors.py
xctestrunner/xctestrunner/shared/plist_util.py external/xctestrunner/xctestrunner/shared/plist_util.py
xctestrunner/xctestrunner/shared/provisioning_profile.py external/xctestrunner/xctestrunner/shared/provisioning_profile.py
xctestrunner/xctestrunner/shared/xcode_info_util.py external/xctestrunner/xctestrunner/shared/xcode_info_util.py
xctestrunner/xctestrunner/simulator_control/__init__.py external/xctestrunner/xctestrunner/simulator_control/__init__.py
xctestrunner/xctestrunner/simulator_control/simtype_profile.py external/xctestrunner/xctestrunner/simulator_control/simtype_profile.py
xctestrunner/xctestrunner/simulator_control/simulator_util.py external/xctestrunner/xctestrunner/simulator_control/simulator_util.py
xctestrunner/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/project.pbxproj external/xctestrunner/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/project.pbxproj
xctestrunner/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXctest.xcscheme external/xctestrunner/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXctest.xcscheme
xctestrunner/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXcuitest.xcscheme external/xctestrunner/xctestrunner/test_runner/TestProject/TestProject.xcodeproj/xcshareddata/xcschemes/TestProjectXcuitest.xcscheme
xctestrunner/xctestrunner/test_runner/__init__.py external/xctestrunner/xctestrunner/test_runner/__init__.py
xctestrunner/xctestrunner/test_runner/dummy_project.py external/xctestrunner/xctestrunner/test_runner/dummy_project.py
xctestrunner/xctestrunner/test_runner/ios_test_runner.py external/xctestrunner/xctestrunner/test_runner/ios_test_runner.py
xctestrunner/xctestrunner/test_runner/logic_test_util.py external/xctestrunner/xctestrunner/test_runner/logic_test_util.py
xctestrunner/xctestrunner/test_runner/runner_exit_codes.py external/xctestrunner/xctestrunner/test_runner/runner_exit_codes.py
xctestrunner/xctestrunner/test_runner/test_summaries_util.py external/xctestrunner/xctestrunner/test_runner/test_summaries_util.py
xctestrunner/xctestrunner/test_runner/xcodebuild_test_executor.py external/xctestrunner/xctestrunner/test_runner/xcodebuild_test_executor.py
xctestrunner/xctestrunner/test_runner/xctest_session.py external/xctestrunner/xctestrunner/test_runner/xctest_session.py
xctestrunner/xctestrunner/test_runner/xctestrun.py external/xctestrunner/xctestrunner/test_runner/xctestrun.py
```

As you can see there's an `xctestrunner` in the map. This leads to a runtime crash because the imports are no longer valid:

```
% bazel-bin/external/xctestrunner/xctestrunner/ios_test_runner.par
Traceback (most recent call last):
  File "/Users/ksmiley/.pyenv/versions/2.7.15/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/ksmiley/.pyenv/versions/2.7.15/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-bin/external/xctestrunner/xctestrunner/ios_test_runner.par/__main__.py", line 32, in <module>
ImportError: No module named shared
```

The difference seems to be the result calculated from this function https://github.com/google/subpar/blob/07ff5feb7c7b113eea593eb6ec50b51099cf0261/subpar.bzl#L97-L111

If I hack this function to remove `../xctestrunner/` from the beginning of the path, I get a valid par.

Is something incorrect with my configuration? Is this use case supported?

**Comment by keith** [comment]
It looks like one solution to this is to change the source in the repo I linked to change the imports and then add `.` in the `imports` build argument. Example https://github.com/google/xctestrunner/pull/2

Is this the right way to solve this?

**Comment by keith** [comment]
@brandjon do you have a few minutes to take a look at this? 🙏
